build:
  image: default-bionic
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

  environment:
    php: 8.3.1

filter:
  excluded_paths:
    - "Resources/*"
    - "Tests/*"
    - "var/*"
    - "build/*"
  dependency_paths:
    - "vendor/*"
